name: CI
on:
  - push
  - pull_request
permissions: {}
jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
      - run: npm install --ignore-scripts
      - run: npm run build:dist
      - run: npm run lint-cpp
      - run: npm run lint-js
      - run: npm run lint-types
      - run: npm run lint-publish
  build-native:
    permissions:
      contents: read
    needs: lint
    name: "build-${{ matrix.platform }} [Node.js ${{ matrix.nodejs_version_major }}] ${{ matrix.package && '[package]' }}"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            container: rockylinux:8
            nodejs_arch: x64
            nodejs_version: "^20.9.0"
            nodejs_version_major: 20
            platform: linux-x64
            package: true
          - os: ubuntu-24.04
            container: rockylinux:8
            nodejs_arch: x64
            nodejs_version: "^22"
            nodejs_version_major: 22
            platform: linux-x64
          - os: ubuntu-24.04-arm
            container: arm64v8/rockylinux:8
            nodejs_arch: arm64
            nodejs_version: "^20.9.0"
            nodejs_version_major: 20
            platform: linux-arm64
            package: true
          - os: ubuntu-24.04-arm
            container: arm64v8/rockylinux:8
            nodejs_arch: arm64
            nodejs_version: "^22"
            nodejs_version_major: 22
            platform: linux-arm64
          - os: ubuntu-24.04-arm
            container: arm64v8/rockylinux:8
            nodejs_arch: arm64
            nodejs_version: "^24"
            nodejs_version_major: 24
            platform: linux-arm64
    steps:
      - name: Dependencies (Rocky Linux glibc)
        if: contains(matrix.container, 'rockylinux')
        run: |
          dnf install -y gcc-toolset-14-gcc-c++ make git python3.12 fontconfig
          echo "/opt/rh/gcc-toolset-14/root/usr/bin" >> $GITHUB_PATH
      - name: Dependencies (Linux musl)
        if: contains(matrix.container, 'alpine')
        run: apk add build-base git python3 fontconfig --update-cache
      - name: Dependencies (Python - macOS, Windows)
        if: contains(matrix.os, 'macos') || contains(matrix.os, 'windows')
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
      - name: Dependencies (Node.js)
        if: "!contains(matrix.platform, 'linuxmusl')"
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.nodejs_version }}
          architecture: ${{ matrix.nodejs_arch }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: npm install
      - run: npm run build:dist
      - run: npm run build
      - run: npm run test-unit
      - if: matrix.package
        run: |
          npm run package-from-local-build
          npm run lint-publish -- npm/${{ matrix.platform }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.package
        with:
          name: ${{ matrix.platform }}
          path: npm/${{ matrix.platform }}
          retention-days: 1
          if-no-files-found: error
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    needs:
      - build-native
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: npm
      - name: Create npm workspace tarball
        run: tar -vcaf npm-workspace.tar.xz --directory npm --exclude=from-local-build.js .
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Populate distribution directory
        run: npm run build:dist
      - name: Populate WebAssembly wrapper packages
        run: npm run package-wasm-wrappers
      - name: Create release notes
        run: npm run package-release-notes
      - name: Create GitHub release for tag
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            --notes-file release-notes.md \
            ${{ contains(github.ref, '-rc') && '--prerelease --latest=false' || '' }} \
            ${GITHUB_REF_NAME} \
            npm-workspace.tar.xz
      - name: Publish platform-specific npm packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: cd npm && npm publish --provenance --workspaces --tag=${{ contains(github.ref, '-rc') && 'next' || 'latest' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish sharp npm package
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --provenance --tag=${{ contains(github.ref, '-rc') && 'next' || 'latest' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
